### ISSUE TITLE
Android64 play daily levels

### ISSUE THREAD

**Issue by LumerGD120** [Cvolton/miscbugfixes-geode#6]
I always crash when i press the play button on daily levels

**Comment by Cvolton** [comment]
this is a known issue with older versions of jukebox and possibly autonong, if you have these mods installed, make sure you have the latest version

**Comment by LumerGD120** [comment]
> this is a known issue with older versions of jukebox and possibly autonong, if you have these mods installed, make sure you have the latest version

Ey make this issue closed
